### PR TITLE
Sign up bug fix

### LINKED ISSUE #298: A lead that got an invite cant sign up
I asked her for a screenshot of what she's submitting to see if there were any red flags, but I'm not seeing any. Can you both take a look to see if anything flags for you?

IMG_0029

### PR DESCRIPTION
**Pull request by littleforest**
closes #298

### CODE REVIEW

File: app/controllers/api/v1/users_controller.rb [hunk 1]
```diff
@@ -4,7 +4,7 @@ class API::V1::UsersController < API::V1::APIController
   ## TODO remove support for leads overriding generated passwords once the site 
   ## is opened up to anyone.
   def create
-    existing_user = User.find_by(email: user_params[:email])
+    existing_user = User.find_by(email: user_params[:email].downcase)
```
Comment (Pcushing) [inline app/controllers/api/v1/users_controller.rb]: @littleforest not urgent but in an upcoming release, can we slip in something that'll ensure we're downcasing every email that comes in for user? Bake it right into the `email=` setter so we only ever have downcased emails to deal with in the DB?

Comment (littleforest) [reply app/controllers/api/v1/users_controller.rb]: Sure will do
